LOCAL_DIR := $(GET_LOCAL_DIR)

MEMBASE := 0x02100000 # SDRAM # LGE_CHANGE, taiyou.kang@lge.com, change LK code start address due to increase boot.img over than 8MB #
MEMSIZE := 0x00100000 # 1MB

SCRATCH_ADDR     := 0x2800000

MACH_TYPE := 6577
HAVE_CACHE_PL310 := yes
LK_PROFILING := yes


DEFINES += \
        MEMBASE=$(MEMBASE)\
	SCRATCH_ADDR=$(SCRATCH_ADDR)\
	MACH_TYPE=$(MACH_TYPE)
        
ifeq ($(HAVE_CACHE_PL310), yes)
DEFINES += HAVE_CACHE_PL310
endif

ifeq ($(MTK_FASTBOOT_SUPPORT), yes)
DEFINES += MTK_FASTBOOT_SUPPORT
endif

ifeq ($(LK_PROFILING), yes)
DEFINES += LK_PROFILING
endif 

ifeq ($(TARGET_BUILD_VARIANT),user)
DEFINES += USER_BUILD
endif 

ifeq ($(TARGET_BUILD_VARIANT),userdebug)
DEFINES += FASTBOOT_USERDEBUG
endif
