/*
 * Generated by MTK Drv_CodeGen Version 04.08.0 for MT6575_NP. Copyright MediaTek Inc. (C) 2011.
 * Thu May  9 11:44:38 2013
 * Do Not Modify the File.
 */



#include "pmic_drv.h"




//For PMIC driver use


