include $(MTK_PATH_BUILD)/common.mk
$(call all-modules-src-or-makefile,$(obj),CUSTOM_KERNEL_)
ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/video/  \
           -I$(MTK_PATH_SOURCE)/drivers/video/
obj-n := dummy.o
