BOOT_LOGO=qhd
MTK_PLATFORM=MT6577
MTK_NAND_PAGE_SIZE=4K
GEMINI=yes
MTK_GEMINI_ENHANCEMENT=no
MTK_SHARE_MODEM_CURRENT=2
MTK_SHARE_MODEM_SUPPORT=2
MTK_RAT_WCDMA_PREFERRED=yes
MTK_BSP_PACKAGE=yes
CUSTOM_HAL_IMGSENSOR=imx111_mipi_raw imx119_mipi_raw
CUSTOM_HAL_MAIN_IMGSENSOR=imx111_mipi_raw
CUSTOM_HAL_MSENSORLIB=bmc150
CUSTOM_HAL_SUB_IMGSENSOR=imx119_mipi_raw
CUSTOM_KERNEL_ACCELEROMETER=bma255
CUSTOM_KERNEL_IRRC=irrc
CUSTOM_KERNEL_ALSPS=apds9130
CUSTOM_KERNEL_IMGSENSOR=imx111_mipi_raw imx119_mipi_raw
LCM_HEIGHT=960
LCM_WIDTH=540
CUSTOM_KERNEL_LCM=hx8389b_qhd_dsi_vdo
CUSTOM_KERNEL_MAIN_IMGSENSOR=imx111_mipi_raw
CUSTOM_KERNEL_SOUND=amp_tpa2015d1_tpa6136a2
CUSTOM_KERNEL_ALSPS=apds9130
CUSTOM_KERNEL_SUB_IMGSENSOR=imx119_mipi_raw
CUSTOM_KERNEL_TOUCHPANEL=synaptics_7020
CUSTOM_KERNEL_USB=mt6575
CUSTOM_KERNEL_CHARGEPUMP=lm3639
CUSTOM_KERNEL_MAGNETOMETER=bmm050
CUSTOM_KERNEL_HALLIC=bu52031nvx
CUSTOM_MODEM=lge77hdk_e1_evb_hspa
CUSTOM_UBOOT_LCM=hx8389b_qhd_dsi_vdo
CUSTOM_LK_LCM=hx8389b_qhd_dsi_vdo
#LGE_CHANGE_S : 2012-10-25 aravind.srinivas@lge.com Dome Key LED Driver
CUSTOM_KERNEL_KPRJ=leds-lp5521
CUSTOM_LK_KPRJ=leds-lp5521
#LGE_CHANGE_E : 2012-10-25 aravind.srinivas@lge.com

CUSTOM_HAL_LENS=fm50af dummy_lens
CUSTOM_HAL_MAIN_LENS=fm50af
CUSTOM_HAL_SUB_LENS=dummy_lens 
CUSTOM_KERNEL_LENS=fm50af dummy_lens
CUSTOM_KERNEL_MAIN_LENS=fm50af
CUSTOM_KERNEL_SUB_LENS=dummy_lens

CUSTOM_HAL_FLASHLIGHT=constant_flashlight 
CUSTOM_KERNEL_FLASHLIGHT=constant_flashlight 
CUSTOM_HAL_EEPROM=s24cs64a_eeprom
CUSTOM_KERNEL_EEPROM=s24cs64a_eeprom

MTK_LCM_PHYSICAL_ROTATION=0

DEFAULT_LATIN_IME_LANGUAGES=en_US

MTK_75DISPLAY_ENHANCEMENT_SUPPORT=no

MTK_APKINSTALLER_APP=yes
MTK_ASF_PLAYBACK_SUPPORT=no

MTK_DM_APP=no
MTK_DUAL_MIC_SUPPORT=yes

MTK_EAP_SIM_AKA=yes

MTK_FSCK_MSDOS_MTK=no

MTK_GOOGLEOTA_SUPPORT=no

MTK_LAUNCHER_UNREAD_SUPPORT=no

MTK_MASS_STORAGE=no

MTK_SENSOR_SUPPORT=yes
MTK_SPECIFIC_SM_CAUSE=yes

MTK_SMSREG_APP=no

MTK_TTY_SUPPORT=yes

RESOURCE_OVERLAY_SUPPORT=generic
# LGE_CHANGE_S 20120926 seungwoo.song : Enable MTK_AUDIO_HD_REC_SUPPORT
#MTK_AUDIO_HD_REC_SUPPORT=no
# LGE_CHANGE_E 20120926 seungwoo.song
MTK_AUDIO_GAIN_TABLE_SUPPORT = yes
OPTR_SPEC_SEG_DEF=NONE

MTK_RELEASE_PACKAGE=rel_customer_basic

CUSTOM_KERNEL_BATTERY = battery
MTK_CALENDAR_IMPORTER_APP=no
MTK_FILEMANAGER_APP=no
MTK_FASTBOOT_SUPPORT=yes 
MTK_MAV_SUPPORT=no
MTK_VIDEOPLAYER_APP=no
MTK_ENABLE_VIDEO_EDITOR=no
MTK_VLW_APP=no
MTK_VT3G324M_SUPPORT=no
MTK_WEATHER_PROVIDER_APP=no
MTK_WEATHER_WIDGET_APP=no
MTK_WORLD_CLOCK_WIDGET_APP=no
MTK_SOUNDRECORDER_APP=yes
MTK_WVDRM_SUPPORT=no
MTK_DRM_APP=no
MTK_THEMEMANAGER_APP=no
MTK_WEATHER3D_WIDGET=no

MTK_BT_21_SUPPORT = yes
MTK_BT_30_HS_SUPPORT = no
MTK_BT_30_SUPPORT = yes
MTK_BT_40_LE_STANDALONE = no
MTK_BT_40_SUPPORT = no
MTK_BT_FM_OVER_BT_VIA_CONTROLLER = no
MTK_BT_POWER_EFFICIENCY_ENHANCEMENT = no
MTK_BT_PROFILE_A2DP = yes
MTK_BT_PROFILE_AVRCP = yes
MTK_BT_PROFILE_AVRCP13 = yes
MTK_BT_PROFILE_AVRCP14 = no
MTK_BT_PROFILE_BIP = no
MTK_BT_PROFILE_BPP = no
MTK_BT_PROFILE_DUN = no
MTK_BT_PROFILE_FTP = yes
MTK_BT_PROFILE_HFP = yes
MTK_BT_PROFILE_HIDH= yes
MTK_BT_PROFILE_MANAGER = yes
MTK_BT_PROFILE_MAPC = no
MTK_BT_PROFILE_MAPS = yes
MTK_BT_PROFILE_OPP = yes
MTK_BT_PROFILE_PAN = yes
MTK_BT_PROFILE_PBAP = yes
MTK_BT_PROFILE_PRXM = no
MTK_BT_PROFILE_PRXR = no
MTK_BT_PROFILE_SIMAP = no
MTK_BT_PROFILE_SPP = yes
MTK_BT_PROFILE_TIMEC = no
MTK_BT_PROFILE_TIMES = no
MTK_BICR_SUPPORT=no

MTK_TETHERINGIPV6_SUPPORT=no

HAVE_SRSAUDIOEFFECT_FEATURE=no

MTK_NFC_SUPPORT = no 
MTK_NFC_INSIDE = no 
ENCRY_PARTITION_SUPPORT=yes
MTK_MULTI_PATCH_SUPPORT=yes
